stages:
  - build
  - test

build_api:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  tags:
    - student
  script:
    - cd api
    - dotnet restore
    - dotnet build --configuration Release
  rules:
    - if: '$CI_COMMIT_BRANCH'

test_api:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  tags:
    - student
  script:
    - cd api
    - dotnet restore
    - dotnet test
  rules:
    - if: '$CI_COMMIT_BRANCH'